# Generated by Django 4.1.3 on 2022-12-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='UrunRENK',
            field=models.CharField(choices=[('KIRMIZI', 'kırmızı'), ('MAVI', 'mavi'), ('YESIL', 'yeşil'), ('SARI', 'sarı'), ('TURUNCU', 'turuncu'), ('SIYAH', 'siyah')], max_length=20),
        ),
     
    ]
