# Generated by Django 4.1.3 on 2022-12-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_alter_urun_urunrenk_urunozellik'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrunOzellik',
            fields=[
                ('UrunOzID', models.AutoField(primary_key=True, serialize=False)),
                ('UrunOzType', models.CharField(max_length=50)),
                ('UrunOzValue', models.CharField(max_length=50)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.urun')),
            ],
            options={
                'verbose_name': 'UrunOzellik',
                'db_table': 'UrunOzellik',
            },
        ),
    ]
