# Generated by Django 4.1.3 on 2022-12-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_rename_urunid_urunimg_urunimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunimg',
            old_name='UrunImages',
            new_name='UrunID',
        ),
    ]
