# Generated by Django 4.1.3 on 2022-12-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_rename_urunimages_urunimg_urunid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunimg',
            name='UrunID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='ProductApp.urun'),
        ),
        migrations.AlterField(
            model_name='urunozellik',
            name='UrunID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozellikler', to='ProductApp.urun'),
        ),
    ]
