# Generated by Django 4.1.3 on 2022-12-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0006_alter_urunimg_urunid_alter_urunozellik_urunid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='AltKategoriID',
            new_name='AltKategori',
        ),
        migrations.RenameField(
            model_name='urun',
            old_name='FirmaID',
            new_name='Firma',
        ),
        migrations.RenameField(
            model_name='urun',
            old_name='KategoriID',
            new_name='Kategori',
        ),
        migrations.RenameField(
            model_name='urun',
            old_name='MarkaID',
            new_name='Marka',
        ),
    ]
