# Generated by Django 4.1.3 on 2022-12-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0008_rename_urunid_urunimg_urun_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altkategori',
            old_name='KategoriID',
            new_name='Kategori',
        ),
    ]
