# Generated by Django 4.1.3 on 2022-11-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('UserSurename', models.CharField(max_length=50)),
                ('UserGSM', models.CharField(max_length=11)),
                ('UserEMAIL', models.CharField(max_length=100)),
                ('UserPASSWORD', models.CharField(max_length=128)),
                ('TOKEN', models.CharField(max_length=128)),
                ('TOKENDATE', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'User',
            },
        ),
    ]
