# Generated by Django 4.1.3 on 2022-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TOKEN',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
