# Generated by Django 4.1.3 on 2022-11-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_user_token_alter_user_tokendate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TOKENDATE',
            field=models.DateTimeField(),
        ),
    ]
