# Generated by Django 4.1.3 on 2022-11-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_user_tokendate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TOKEN',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
