# Generated by Django 4.1.3 on 2022-12-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
        ('UserApp', '0007_alter_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyeList',
            fields=[
                ('UyeListID', models.AutoField(primary_key=True, serialize=False)),
                ('UyeListADI', models.CharField(max_length=50)),
                ('UyeListTARIH', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'verbose_name': 'UyeList',
                'db_table': 'UyeList',
            },
        ),
        migrations.CreateModel(
            name='UrunYorum',
            fields=[
                ('UrunYorumID', models.AutoField(primary_key=True, serialize=False)),
                ('Yorum', models.CharField(max_length=200)),
                ('YorumTARIH', models.DateTimeField(auto_now_add=True)),
                ('YorumDURUM', models.BooleanField(default=True)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.urun')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'verbose_name': 'UrunYorum',
                'db_table': 'UrunYorum',
            },
        ),
        migrations.CreateModel(
            name='UrunList',
            fields=[
                ('UrunListID', models.AutoField(primary_key=True, serialize=False)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.urun')),
                ('UyeListID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.uyelist')),
            ],
            options={
                'verbose_name': 'UrunList',
                'db_table': 'UrunList',
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('SiparisID', models.AutoField(primary_key=True, serialize=False)),
                ('SiparisADRES', models.CharField(max_length=300)),
                ('SiparisADET', models.IntegerField()),
                ('SiparisFIYAT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SiparisDURUM', models.CharField(choices=[('HAZIRLANMA ASAMASINDA', 'Hazırlanma aşamasında'), ('KARGOYA VERILDI', 'Kargoya verildi'), ('TESLIM EDILDI', 'Teslim edildi')], max_length=50)),
                ('SiparisTARIH', models.DateTimeField(auto_now_add=True)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductApp.urun')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'verbose_name': 'Siparis',
                'db_table': 'Siparis',
            },
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('SepetID', models.AutoField(primary_key=True, serialize=False)),
                ('UrunADET', models.IntegerField()),
                ('UrunTARIH', models.DateTimeField(auto_now_add=True)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.urun')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'verbose_name': 'Sepet',
                'db_table': 'Sepet',
            },
        ),
    ]
