# Generated by Django 4.1.3 on 2022-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_uyelist_urunyorum_urunlist_siparis_sepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TOKEN',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
