# Generated by Django 4.1.3 on 2022-12-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0009_rename_kategoriid_altkategori_kategori'),
        ('UserApp', '0009_alter_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sepet',
            old_name='UrunID',
            new_name='Urun',
        ),
        migrations.RenameField(
            model_name='sepet',
            old_name='UserID',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='siparis',
            old_name='UrunID',
            new_name='Urun',
        ),
        migrations.RenameField(
            model_name='siparis',
            old_name='UserID',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='urunlist',
            old_name='UyeListID',
            new_name='UyeList',
        ),
        migrations.RenameField(
            model_name='urunyorum',
            old_name='UrunID',
            new_name='Urun',
        ),
        migrations.RenameField(
            model_name='urunyorum',
            old_name='UserID',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='uyelist',
            old_name='UserID',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='urunlist',
            name='UrunID',
        ),
        migrations.AddField(
            model_name='urunlist',
            name='Urun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Urun', to='ProductApp.urun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='TOKEN',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='TOKENDATE',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
