# Generated by Django 4.1.3 on 2022-12-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_rename_urunid_sepet_urun_rename_userid_sepet_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='SiparisADRESALICI',
            field=models.CharField(default='Girilmedi', max_length=50),
        ),
        migrations.AddField(
            model_name='siparis',
            name='SiparisADRESALICIGSM',
            field=models.CharField(default='Girilmedi', max_length=11),
        ),
        migrations.AddField(
            model_name='siparis',
            name='SiparisADRESALICITC',
            field=models.CharField(default='Girilmedi', max_length=11),
        ),
        migrations.AddField(
            model_name='siparis',
            name='SiparisADRESBASLIK',
            field=models.CharField(default='Girilmedi', max_length=50),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='SiparisDURUM',
            field=models.CharField(choices=[('IPTAL EDILDI', 'iptal edildi'), ('HAZIRLANMA ASAMASINDA', 'Hazırlanma aşamasında'), ('KARGOYA VERILDI', 'Kargoya verildi'), ('TESLIM EDILDI', 'Teslim edildi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='urunlist',
            name='UyeList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UrunList', to='UserApp.uyelist'),
        ),
    ]
